# -- test/testdata/packager/export_imported/a/__package.rb --
class <emptyTree><<C <root>>> < (::<todo sym>)
  class <emptyTree>::<C A>::<C <PackageSpecRegistry>><<C <todo sym>>> < (<emptyTree>::<C PackageSpec>)
    <self>.import(<emptyTree>::<C B>::<C <PackageSpecRegistry>>)

    <self>.export(::<root>::<C B>::<C BClass>)
  end
end
# -- test/testdata/packager/export_imported/b/__package.rb --
class <emptyTree><<C <root>>> < (::<todo sym>)
  class <emptyTree>::<C B>::<C <PackageSpecRegistry>><<C <todo sym>>> < (<emptyTree>::<C PackageSpec>)
    <self>.export(::<root>::<C B>::<C BClass>)
  end
end
# -- test/testdata/packager/export_imported/b/b.rb --
class <emptyTree><<C <root>>> < (::<todo sym>)
  class <emptyTree>::<C B>::<C BClass><<C <todo sym>>> < (::<todo sym>)
  end
end
