# -- test/testdata/packager/import_subpackage/a/__package.rb --
class <emptyTree><<C <root>>> < (::<todo sym>)
  class <emptyTree>::<C Root>::<C <PackageSpecRegistry>><<C <todo sym>>> < (<emptyTree>::<C PackageSpec>)
    <self>.import(<emptyTree>::<C Root>::<C B>::<C <PackageSpecRegistry>>)
  end
end
# -- test/testdata/packager/import_subpackage/a/b/__package.rb --
class <emptyTree><<C <root>>> < (::<todo sym>)
  class <emptyTree>::<C Root>::<C B>::<C <PackageSpecRegistry>><<C <todo sym>>> < (<emptyTree>::<C PackageSpec>)
    <self>.export(::<root>::<C Root>::<C B>::<C Foo>)
  end
end
# -- test/testdata/packager/import_subpackage/a/b/foo.rb --
class <emptyTree><<C <root>>> < (::<todo sym>)
  module <emptyTree>::<C Root>::<C B>::<C Foo><<C <todo sym>>> < ()
  end
end
